#ifndef DISPLAY_CONFIG_H
#define DISPLAY_CONFIG_H

#define TFT_WIDTH  240
#define TFT_HEIGHT 320

#define TFT_ROTATION 2

#define SPLASH_DURATION_MS 3000

#define SPLASH_BACKGROUND TFT_BLACK
#define SPLASH_TEXT_COLOR TFT_WHITE

#endif