#ifndef PERSONALIZATION_H
#define PERSONALIZATION_H

#define DEVICE_NAME     "3x0c3t BO4RD"
#define DEVICE_MODEL    "DIAGNOSTIC"
#define DEVICE_VERSION  "v2.0-diag"

#define SPLASH_TITLE    DEVICE_NAME
#define SPLASH_SUBTITLE DEVICE_MODEL
#define SPLASH_VERSION  DEVICE_VERSION

#endif